baseurl = "https://mikeyangpro.github.io/"
languageCode = "en-us"
publishDir = "../mikeyangpro.github.io"
title = "Mike Quant"
# Enable comments by entering your Disqus shortname
disqusShortname = "gitr"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-hikari-theme"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Mike Yang"
	description = "Wus up dawg."
	copyright = "POWERED BY [HUGO](//gohugo.io) - THEME: [HIKARI](//github.com/digitalcraftsman/hugo-hikari-theme) - © JOHN DOE"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Hi, I'm Mike Yang."
	bio = "M.Sc AMath. Quant. Likes market, R, cool models/packages and photography."
	subscribe = "Subscribe"
	followme = "Follow me on"

	# Enable Google search
	search_enabled = true
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "Github"
		url = "//github.com/mikeyangpro"

	[[params.offcanvas.socialnetworks]]
		name = "Linkedin"
		url = "//linkedin.com/mikeyangpro"
